services:
  - type: web
    name: ai-studio-ide-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run generate && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: STUDIO_API_KEY
        value: exs-d5e7kgfgi27c73981tmg
